<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <OutputType>Library</OutputType>
    <NoStandardLibraries>false</NoStandardLibraries>
    <AssemblyName>BrewsicCore</AssemblyName>
    <PreBuildEvent>echo F|xcopy "%HOMEPATH%\OneDrive - Group Online A S\Documents\NesDev\snes\obj\snes.sfc.spc" "$(ProjectDir)spcdriver.bin" /y</PreBuildEvent>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Prevent Errorhandling|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\Prevent Errorhandling\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="spcdriver.bin" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
    <PackageReference Include="NAudio" Version="2.1.0" />
    <PackageReference Include="NAudio.Asio" Version="2.1.0" />
    <PackageReference Include="NAudio.Core" Version="2.1.0" />
    <PackageReference Include="NAudio.Lame" Version="2.0.1" />
    <PackageReference Include="NAudio.Midi" Version="2.1.0" />
    <PackageReference Include="NAudio.Wasapi" Version="2.1.0" />
    <PackageReference Include="NAudio.WinForms" Version="2.1.0" />
    <PackageReference Include="NAudio.WinMM" Version="2.1.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Security.AccessControl" Version="6.0.1" />
    <PackageReference Include="System.Security.Principal.Windows" Version="5.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ProjectExtensions>
    <VisualStudio AllowExistingFolder="true" />
  </ProjectExtensions>
</Project>